### ISSUE TITLE
VIP Clarity

### ISSUE THREAD

**Issue by ronaldpetty** [starkandwayne/ultimate-guide-to-bosh#32]
Hello,

https://ultimateguidetobosh.com/networking/#virtual-ip-addresses

Discusses the use of default vs elastic static IPs.  In the example, it talks how we might use AWS allocated EIP (elastic) versus our own static_ips (default), but the example shows a combination of both.

```
instance_groups:
- name: zookeeper-instances
  instances: 5
  networks:
  - name: default
    default: [dns, gateway]
  - name: elastic
    static_ips:
    - 10.0.0.220
    - 10.0.0.221
    - 10.0.0.222
    - 10.0.0.223
    - 10.0.0.224
```

It doesn't state that if the EIP fails it will fall back to the static ips?  Or is this a typo where the static ips should be:

```
instance_groups:
- name: zookeeper-instances
  instances: 5
  networks:
  - name: default
    default: [dns, gateway]
  - name: elastic
    static_ips:
    - 54.1.2.3
    - 56.2.3.4
    - 58.4.5.6
    - 123.1.2.3
    - 124.2.3.4
```

Can you help me understand what is the outcome?  

Great job on book/blog ~~ boog/blok?
